name: Beta Deploy to cPanel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & SSH Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: ⬇️ Install dependencies
        run: pnpm install

      - name: 🛠️ Build Next.js application
        env:
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        run: pnpm run build

      - name: 📦 Prepare deployment
        run: |
          cd out
          tar -czf ../deploy.tar.gz .

      - name: 🔐 Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🔐 Install sshpass
        run: sudo apt-get install -y sshpass

      - name: 🧹 Clean remote directory
        env:
          TERM: xterm
        run: |
          export SSHPASS=${{ secrets.SSH_PASSWORD }}
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
          mkdir -p public_html &&
          cd public_html &&
          find . -mindepth 1 -maxdepth 1 ! -name "docs" ! -name "images" -exec rm -rf {} +'

      - name: 📂 Transfer and extract files
        env:
          TERM: xterm
        run: |
          export SSHPASS=${{ secrets.SSH_PASSWORD }}
          sshpass -e scp -o StrictHostKeyChecking=no deploy.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:public_html/
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
          cd public_html &&
          tar -xzf deploy.tar.gz &&
          rm deploy.tar.gz'
